---
argument_specs:
  main:
    short_description: Configure Netplan
    description:
      - The role configures networking with Netplan.
    version_added: 0.1.0
    author:
      - Alexey Busygin
    options:
      netplan_config:
        type: str
        required: true
        description:
          - Specifies path to the Netplan configuration file template (Jinja).
        version_added: 0.1.0
      netplan_remove_unmanaged_configs:
        type: bool
        default: true
        required: false
        description:
          - >
              Remove Netplan configuration files that are not managed by this
              role.
        version_added: 0.1.0
      netplan_config_template_lstrip_blocks:
        type: bool
        default: true
        required: false
        description:
          - >
              The value of the "lstrip_blocks" parameter to be applied, when
              rendering Netplan configuration from the specified Jinja template.
        version_added: 0.1.0
